insert into _room (roomID, roomNum, capacity, type, buildingID) values (1, '3775', 73, 'Lecture Hall', 1);
insert into _room (roomID, roomNum, capacity, type, buildingID) values (2, '75584', 78, 'Lab', 1);
insert into _room (roomID, roomNum, capacity, type, buildingID) values (3, '9', 168, 'Lab', 1);
insert into _room (roomID, roomNum, capacity, type, buildingID) values (4, '735', 35, 'Lecture Hall', 1);
insert into _room (roomID, roomNum, capacity, type, buildingID) values (5, '4432', 57, 'Lecture Hall', 1);
insert into _room (roomID, roomNum, capacity, type, buildingID) values (6, '12945', 45, 'Lecture Hall', 1);
insert into _room (roomID, roomNum, capacity, type, buildingID) values (7, '8019', 117, 'Lecture Hall', 2);
insert into _room (roomID, roomNum, capacity, type, buildingID) values (8, '22861', 217, 'Lecture Hall', 2);
insert into _room (roomID, roomNum, capacity, type, buildingID) values (9, '41', 87, 'Classroom', 2);
insert into _room (roomID, roomNum, capacity, type, buildingID) values (10, '4057', 226, 'Classroom', 2);
insert into _room (roomID, roomNum, capacity, type, buildingID) values (11, '3975', 199, 'Classroom', 3);
insert into _room (roomID, roomNum, capacity, type, buildingID) values (12, '3929', 164, 'Classroom', 3);
insert into _room (roomID, roomNum, capacity, type, buildingID) values (13, '66', 164, 'Classroom', 3);
insert into _room (roomID, roomNum, capacity, type, buildingID) values (14, '4744', 139, 'Classroom', 3);
insert into _room (roomID, roomNum, capacity, type, buildingID) values (15, '6', 53, 'Lab', 4);
insert into _room (roomID, roomNum, capacity, type, buildingID) values (16, '30322', 246, 'Lab', 4);
insert into _room (roomID, roomNum, capacity, type, buildingID) values (17, '5', 162, 'Lab', 5);
insert into _room (roomID, roomNum, capacity, type, buildingID) values (18, '9', 189, 'Lab', 5);
insert into _room (roomID, roomNum, capacity, type, buildingID) values (19, '046', 124, 'Lecture Hall', 5);
insert into _room (roomID, roomNum, capacity, type, buildingID) values (20, '63', 25, 'Lecture Hall', 5);
