insert into _course (courseID, title, credit_hours, courseNum, subject, prerequisiteID, deptID) values (1, 'Human Computer Interactions', 3, 451, 'Mathematics', NULL, 1);
insert into _course (courseID, title, credit_hours, courseNum, subject, prerequisiteID, deptID) values (2, 'Intro to Computer Science', 4, 223, 'Mathematics', NULL, 1);
insert into _course (courseID, title, credit_hours, courseNum, subject, prerequisiteID, deptID) values (3, 'University Choral Ensemble', 4, 301, 'Music', NULL, 4);
insert into _course (courseID, title, credit_hours, courseNum, subject, prerequisiteID, deptID) values (4, 'Principles of Chemistry', 4, 395, 'Sciences', NULL, 5);
insert into _course (courseID, title, credit_hours, courseNum, subject, prerequisiteID, deptID) values (5, 'Finite Mathematics', 4, 407, 'Mathematics', NULL, 1);
insert into _course (courseID, title, credit_hours, courseNum, subject, prerequisiteID, deptID) values (6, 'Intro to Psychology', 3, 103, 'Sciences', NULL, 2);
insert into _course (courseID, title, credit_hours, courseNum, subject, prerequisiteID, deptID) values (7, 'Molecular Biology', 4, 365, 'Sciences', NULL, 2);
insert into _course (courseID, title, credit_hours, courseNum, subject, prerequisiteID, deptID) values (8, 'Jazz Piano', 4, 256, 'Music', NULL, 4);
insert into _course (courseID, title, credit_hours, courseNum, subject, prerequisiteID, deptID) values (9, 'Jazz Improvisation', 4, 416, 'Music', 8, 4);
insert into _course (courseID, title, credit_hours, courseNum, subject, prerequisiteID, deptID) values (10, 'Introduction to Programming', 4, 264, 'Mathematics', NULL, 1);
insert into _course (courseID, title, credit_hours, courseNum, subject, prerequisiteID, deptID) values (11, 'Information Systems', 3, 481, 'Mathematics', NULL, 1);
insert into _course (courseID, title, credit_hours, courseNum, subject, prerequisiteID, deptID) values (12, 'Chemical Modeling', 3, 165, 'Sciences', NULL, 5);
insert into _course (courseID, title, credit_hours, courseNum, subject, prerequisiteID, deptID) values (13, 'Biological Mechanisms', 3, 197, 'Sciences', NULL, 2);
insert into _course (courseID, title, credit_hours, courseNum, subject, prerequisiteID, deptID) values (14, 'Economical Principles', 4, 103, 'Business', NULL, 3);
insert into _course (courseID, title, credit_hours, courseNum, subject, prerequisiteID, deptID) values (15, 'Statistics and Wealth', 3, 176, 'Business', NULL, 3);
insert into _course (courseID, title, credit_hours, courseNum, subject, prerequisiteID, deptID) values (16, 'Topics in Business', 4, 464, 'Business', 14, 3);
insert into _course (courseID, title, credit_hours, courseNum, subject, prerequisiteID, deptID) values (17, 'Introduction to Sociology', 4, 106, 'Humanities', NULL, 2);
insert into _course (courseID, title, credit_hours, courseNum, subject, prerequisiteID, deptID) values (18, 'Math Foundations of Informatics', 4, 268, 'Mathematics', NULL, 1);
insert into _course (courseID, title, credit_hours, courseNum, subject, prerequisiteID, deptID) values (19, 'Organic Chemistry I', 3, 251, 'Sciences', NULL, 5);
insert into _course (courseID, title, credit_hours, courseNum, subject, prerequisiteID, deptID) values (20, 'Behavioral Psychology', 3, 346, 'Sciences', 6, 2);


update _course set subject='Mathematics' where courseID=1;
update _course set subject='Mathematics' where courseID=2;
update _course set subject='Music' where courseID=3;
update _course set subject='Sciences' where courseID=4;
update _course set subject='Mathematics' where courseID=5;
update _course set subject='Sciences' where courseID=6;
update _course set subject='Sciences' where courseID=7;
update _course set subject='Music' where courseID=8;
update _course set subject='Music' where courseID=9;
update _course set subject='Mathematics' where courseID=10;
update _course set subject='Mathematics' where courseID=11;
update _course set subject='Sciences' where courseID=12;
update _course set subject='Sciences' where courseID=13;
update _course set subject='Business' where courseID=14;
update _course set subject='Business' where courseID=15;
update _course set subject='Business' where courseID=16;
update _course set subject='Humanities' where courseID=17;
update _course set subject='Mathematics' where courseID=18;
update _course set subject='Sciences' where courseID=19;
update _course set subject='Sciences' where courseID=20;
